/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryList: typeof import('./components/categories/CategoryList.vue')['default']
    CategoryListItem: typeof import('./components/categories/CategoryListItem.vue')['default']
    DateLabel: typeof import('./components/uikit/DateLabel.vue')['default']
    ForumList: typeof import('./components/forums/ForumList.vue')['default']
    PluralizeLabel: typeof import('./components/uikit/PluralizeLabel.vue')['default']
    PostEditor: typeof import('./components/posts/PostEditor.vue')['default']
    PostList: typeof import('./components/posts/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavBar: typeof import('./components/TheNavBar.vue')['default']
    ThreadList: typeof import('./components/threads/ThreadList.vue')['default']
  }
}
