/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DateLabel: typeof import('./components/uikit/DateLabel.vue')['default']
    PostEditor: typeof import('./components/posts/PostEditor.vue')['default']
    PostList: typeof import('./components/posts/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreadList: typeof import('./components/threads/ThreadList.vue')['default']
  }
}
